### ISSUE TITLE
Terraform exists when provisioning a module 

### ISSUE THREAD

**Issue by yossi-r** [terraform-providers/terraform-provider-bigip#234] opened 2020-01-15 01:04 UTC
terraform exists after posting the following declaration (which provisions ASM) :
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "webhook": "https://example.com/myHook",
    "label": "my BIG-IP declaration for declarative onboarding",
    "Common": {
        "class": "Tenant",
        "hostname":  "${hostname}",
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org",
                "2.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal",
            "asm": "nominal"
        },
        "internal": {
            "class": "VLAN",
            "tag": 4093,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": false
                }
            ],
            "cmpHash": "src-ip"
        },
        "internal-self": {
            "class": "SelfIp",
            "address":  "${private_ip}",
            "vlan": "internal",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
        "external": {
            "class": "VLAN",
            "tag": 4094,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": false
                }
            ],
            "cmpHash": "src-ip"
        },
        "external-self": {
            "class": "SelfIp",
            "address": "${public_ip}",
            "vlan": "external",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
        "dbvars": {
        	"class": "DbVariables",
        	"ui.advisory.enabled": true,
        	"ui.advisory.color": "green",
        	"ui.advisory.text": "${advisory_text}"
        }
    }
}

**Comment by papineni87** [comment] 2020-01-15 14:46
can you enable debug logs and give us the error message when applying the plan ( to enable debug logs : export TF_LOG=DEBUG )

**Comment by RavinderReddyF5** [comment] 2020-01-16 06:18
@yossi-r 
can you please provide us exact error you are getting.

**Comment by focrensh** [comment] 2020-04-28 14:57
@yossi-r I believe this is a duplicate of #243

**Closed by focrensh** 2020-04-28 14:57 UTC
Labels: duplicate
