### ISSUE TITLE
Cannot create bigip_ssl_key or bigip_ssl_certificate

### ISSUE THREAD

**Issue by ajchiarello** [terraform-providers/terraform-provider-bigip#226] opened 2020-01-08 16:35 UTC
When attempting to create the ssl_key or certificate resources, I get the following error:

> Error in Importing certificate key (mudpit.key): HTTP 401 :: {"code":401,"message":"Authorization failed: user=https://localhost/mgmt/shared/authz/users/svc.k8sbigipcert resource=/mgmt/shared/file-transfer/uploads/mudpit.key verb=POST uri:http://localhost:8100/mgmt/shared/file-transfer/uploads/mudpit.key referrer:10.96.118.34 sender:10.96.118.34","referer":"10.96.118.34","restOperationId":418409362,"kind":":resterrorresponse"}

These resources fail even when the account is given full administrator privileges.

Here is the terraform code I am using to create this:

> resource "bigip_ssl_key" "cluster" {
>   provider  = bigip.certificate
>   name      = "${var.project_name}.key"
>   content   = acme_certificate.cluster.private_key_pem
>   partition = "/K8S/"
> }

I'm on terraform version 0.12.18 & bigip v 1.1.1

**Comment by RavinderReddyF5** [comment] 2020-01-09 08:01
Hi @ajchiarello 
From the errors it looks like Authorization failed for provider, could you please check provider IP,Username,passowrd/token are properly entered. 


I was trying to reproduce issue locally but i am able to import certificate/key onto BIGIP.

Logs:

**terraform apply**
```


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ssl_key.test-cert will be created
  + resource "bigip_ssl_key" "test-cert" {
      + content   = (sensitive value)
      + id        = (known after apply)
      + name      = "serverkey.key"
      + partition = "ravinder"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ssl_key.test-cert: Creating...
bigip_ssl_key.test-cert: Creation complete after 1s [id=serverkey.key]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**terraform config:**

```
provider "bigip" {
  address = "xxx.xxx.xxx.xxx"
  alias = "certificate"
  username = "xxxx"
  password = "xxxxxx"
}

resource "bigip_ssl_key" "test-cert" {
        provider = bigip.certificate
        name = "serverkey.key"
        content = "${file("examples/serverkey.key")}"
        #content = serverkey_pem
        partition = "ravinder"
}

```

**Comment by ajchiarello** [comment] 2020-01-09 14:00
I've double-checked the account information several times - and I can use the same credentials to perform this task in the GUI. I also tried giving it a bad username/password to see if I got the same error - which I don't. It looks like the authentication works, but authorization for this task fails. I initially thought it was permission based, but ruled that out when it still failed, even when granting the account administrator rights.

**Comment by RavinderReddyF5** [comment] 2020-01-10 12:23
@ajchiarello 

Hi 
we are not able to reproduce this issue in out local setup, but to debug further on the issue
Can you please help running below python script to upload files to BIGIP and verify it is copied to BIGIP [ **/var/config/rest/downloads** ]

  https://gist.github.com/jasonrahm/40b03b93a5ed9f1fdc8f

```

- To Copy Certificate to BIGIP using Python script.

Step1 : python <ScriptName.py> <HOST_IP> <USER_NAME> <CERTIFICATE/KEY>

- To install Certificate from local path on BIGIP

Step2: curl -sk -u <USER_NAME>:<Password> -H "Content-Type: application/json" -X POST https://<HOST_IP>/mgmt/tm/sys/crypto/cert -d '{"command":"install","name":"<cert_name>","from-local-file":"/var/config/rest/downloads/<cert_name>"}'

```

**Comment by ajchiarello** [comment] 2020-01-10 15:23
@RavinderReddyF5 
The python script ran without error, but the attempt create the resource failed with a no such file or directory error. It looks like the copy itself never occurred.

**Comment by RavinderReddyF5** [comment] 2020-01-10 17:45
@ajchiarello 
Do you mean python script not able to copy certificate onto BIGIP[/var/config/rest/downloads] ??
if copy itself fails it should be debug from BIGIP point, it will not fall under under terraform. please confirm.

**Comment by ajchiarello** [comment] 2020-01-10 19:44
@RavinderReddyF5 
Yes - I believe the problem is in BigIP. It appears to not be accepting the upload. I am pursuing this with my networking team and they are opening a ticket with F5.

**Comment by RavinderReddyF5** [comment] 2020-01-11 17:29
@ajchiarello 
Can you please let us know the BIGIP Version you are using?

**Comment by ajchiarello** [comment] 2020-01-13 13:40
@RavinderReddyF5 
We are running BIG-IP 14.1.0.6.

**Comment by RavinderReddyF5** [comment] 2020-01-16 06:21
@ajchiarello 
Have you checked with your network team?? as we are not able to upload certificate/key to BIGIP please work with network team to debug further on why it is not copied.

**Comment by ajchiarello** [comment] 2020-01-16 13:40
@RavinderReddyF5 
I am pursuing this with my networking team and they are opening a ticket with F5. It may be because I running against an F5 self IP instead of the management ip.

**Comment by tbosnjak-ops** [comment] 2020-01-29 18:02
Hi all,

I'm receiving the following message:

`Error: Error in Importing certificate key (/Common/cca_50_chars_long_name.key): HTTP 400 :: {"code":400,"message":"Failed! exit_code (37).\n","errorStack":[],"apiError":26214401}`

this my code:

`provider "bigip" {
  address  = "--------------"
  username = "-------------"
  password = "---------"
}

resource "bigip_ssl_key" "server_ssl_key" {
  partition     = "Common"
  name          = "cca_50_chars_long_name.key"
  content       = var.key_pem
}

resource "bigip_ssl_certificate" "server_ssl_cert" {
  partition     = "Common"
  name          = "cca_50_chars_long_name.crt"
  content       = var.cert_pem
}
`

cert_pem and key_pem are outputs from Venafi provider and are pem certificates.

Any clues will be appreciated.

BTW the provider is in v1.1.1 if the certs are downloaded they seem to be OK

**Comment by RavinderReddyF5** [comment] 2020-01-30 11:59
Hi @tbosnjak-ops 

Can you please try using below python script as mentioned in other comments and let me know the behaviour.



> Hi
> Can you please help running below python script to upload files to BIGIP and verify it is copied to BIGIP [ **/var/config/rest/downloads** ]
> 
> https://gist.github.com/jasonrahm/40b03b93a5ed9f1fdc8f
> 
> ```
> 
> - To Copy Certificate to BIGIP using Python script.
> 
> Step1 : python <ScriptName.py> <HOST_IP> <USER_NAME> <CERTIFICATE/KEY>
> 
> - To install Certificate from local path on BIGIP
> 
> Step2: curl -sk -u <USER_NAME>:<Password> -H "Content-Type: application/json" -X POST https://<HOST_IP>/mgmt/tm/sys/crypto/cert -d '{"command":"install","name":"<cert_name>","from-local-file":"/var/config/rest/downloads/<cert_name>"}'
> ```

**Comment by tbosnjak-ops** [comment] 2020-01-31 09:57
> 
> 
> Hi @tbosnjak-ops
> 
> Can you please try using below python script as mentioned in other comments and let me know the behaviour.
> 
> > Hi
> > Can you please help running below python script to upload files to BIGIP and verify it is copied to BIGIP [ **/var/config/rest/downloads** ]
> > https://gist.github.com/jasonrahm/40b03b93a5ed9f1fdc8f
> > ```
> > 
> > - To Copy Certificate to BIGIP using Python script.
> > 
> > Step1 : python <ScriptName.py> <HOST_IP> <USER_NAME> <CERTIFICATE/KEY>
> > 
> > - To install Certificate from local path on BIGIP
> > 
> > Step2: curl -sk -u <USER_NAME>:<Password> -H "Content-Type: application/json" -X POST https://<HOST_IP>/mgmt/tm/sys/crypto/cert -d '{"command":"install","name":"<cert_name>","from-local-file":"/var/config/rest/downloads/<cert_name>"}'
> > ```
Hi Ravinder,

thank you for trying to help. 

We figured it out. The issue was '/Common/' in the name. This happend since we wanted to use the same variable for the name and the cert in ssl_proifles. :(

Sorry for the pollution of the thread.

BR,
T

**Comment by RavinderReddyF5** [comment] 2020-01-31 10:00
@tbosnjak-ops thanks for Update
 @ajchiarello 
i am closing this issue, if you see any new issue please open separate bug.
Thanks

**Closed by RavinderReddyF5** 2020-01-31 10:00 UTC
